            procedure.AppendLine("SET ANSI_NULLS ON");
            procedure.AppendLine("GO");
            procedure.AppendLine("SET QUOTED_IDENTIFIER ON");
            procedure.AppendLine("GO");
            procedure.AppendLine("CREATE PROCEDURE [dbo].[UpdateCatalogs]");
            procedure.AppendLine("	@catalogs [dbo].[catalogsTable] READONLY,");
            procedure.AppendLine("	@linkToPhotos [dbo].[linkToPhotoTable] READONLY");
            procedure.AppendLine("AS");
            procedure.AppendLine("BEGIN");
            procedure.AppendLine(" ");
            procedure.AppendLine("--    +---------------------------------------------------+");
            procedure.AppendLine("--    | Author:       OLEXANDR LIKHOSHVA                  |");
            procedure.AppendLine("--    | Create date:  2018.02.11 23:45                    |");
            procedure.AppendLine("--    | Copyright:    © 2017-2018  ALL RIGHT RESERVED     |");
            procedure.AppendLine("--    | https://www.linkedin.com/in/olexandrlikhoshva/    |");
            procedure.AppendLine("--    |---------------------------------------------------|");
            procedure.AppendLine("--    | Description:  Procedure for insert or update      |");
            procedure.AppendLine("--    |               CatalogItemEntities                 |");
            procedure.AppendLine("--    +---------------------------------------------------+");
            procedure.AppendLine("--    SET NOCOUNT ON added to prevent extra result sets from");
            procedure.AppendLine("--    interfering with SELECT statements.");
            procedure.AppendLine("--    SET NOCOUNT ON;");
            procedure.AppendLine(" ");
            procedure.AppendLine("	WITH [CatalogForUpdate] AS (SELECT * FROM [CatalogItemEntities] AS [CatalogItems]");
            procedure.AppendLine("	                            WHERE [CatalogItems].[Id] IN (SELECT Id FROM @catalogs))");
            procedure.AppendLine("	UPDATE [ItemsForUpdate]");
            procedure.AppendLine("	SET [ItemsForUpdate].[UID] = [UpdateItems].[UID],");
            procedure.AppendLine("	    [ItemsForUpdate].[Code] = [UpdateItems].[Code],");
            procedure.AppendLine("          [ItemsForUpdate].[Article] = [UpdateItems].[Article],");
            procedure.AppendLine("          [ItemsForUpdate].[Name] = [UpdateItems].[Name],");
            procedure.AppendLine("          [ItemsForUpdate].[Brand_Id] = [BrandItems].[Id],");
            procedure.AppendLine("          [ItemsForUpdate].[BrandName] = [BrandItems].[Name],");
            procedure.AppendLine("          [ItemsForUpdate].[Unit] = [UpdateItems].[Unit],");
            procedure.AppendLine("          [ItemsForUpdate].[EnterpriceNormPack] = [UpdateItems].[EnterpriceNormPack],");
            procedure.AppendLine("          [ItemsForUpdate].[BatchOfSales] = [UpdateItems].[BatchOfSales],");
            procedure.AppendLine("          [ItemsForUpdate].[Balance] = [UpdateItems].[Balance],");
            procedure.AppendLine("          [ItemsForUpdate].[Price] = [UpdateItems].[Price],");
            procedure.AppendLine("          [ItemsForUpdate].[Currency] = [UpdateItems].[Currency],");
            procedure.AppendLine("          [ItemsForUpdate].[Multiplicity] = [UpdateItems].[Multiplicity],");
            procedure.AppendLine("          [ItemsForUpdate].[HasPhotos] = [UpdateItems].[HasPhotos],");
            procedure.AppendLine("          [ItemsForUpdate].[DateOfCreation] = [UpdateItems].[DateOfCreation],");
            procedure.AppendLine("          [ItemsForUpdate].[LastUpdated] = [UpdateItems].[LastUpdated],");
            procedure.AppendLine("          [ItemsForUpdate].[ForceUpdated] = [UpdateItems].[ForceUpdated],");
            procedure.AppendLine("          [ItemsForUpdate].[Status] = [UpdateItems].[Status],");
            procedure.AppendLine("          [ItemsForUpdate].[LastUpdatedStatus] = [UpdateItems].[LastUpdatedStatus],");
            procedure.AppendLine("          [ItemsForUpdate].[Directory_Id] = [Directories].[Id]");
            procedure.AppendLine("      FROM [CatalogForUpdate] AS [ItemsForUpdate]");
            procedure.AppendLine("      INNER JOIN @catalogs AS [UpdateItems] ON [ItemsForUpdate].[Id] = [UpdateItems].[Id]");
            procedure.AppendLine("      LEFT JOIN [BrandItemEntities] AS [BrandItems] ON [UpdateItems].[Brand_Id] = [BrandItems].[Id]");
            procedure.AppendLine("      LEFT JOIN [DirectoryEntities] AS [Directories] ON [UpdateItems].[Directory_Id] = [Directories].[Id]");
            procedure.AppendLine(" ");
            procedure.AppendLine("      INSERT INTO  [CatalogItemEntities]");
            procedure.AppendLine("      ([Id], [UID], [Code], [Article], [Name], [Brand_Id], [BrandName], [Unit], [EnterpriceNormPack],");
            procedure.AppendLine("       [BatchOfSales], [Balance], [Price], [Currency], [Multiplicity], [HasPhotos], [DateOfCreation],");
            procedure.AppendLine("       [LastUpdated], [ForceUpdated], [Status], [LastUpdatedStatus], [Directory_Id])");
            procedure.AppendLine("      SELECT [UpdateItems].[Id], [UpdateItems].[UID], [UpdateItems].[Code], [UpdateItems].[Article],");
            procedure.AppendLine("             [UpdateItems].[Name], [BrandItems].[Id], [BrandItems].[Name], [UpdateItems].[Unit],");
            procedure.AppendLine("             [UpdateItems].[EnterpriceNormPack], [UpdateItems].[BatchOfSales], [UpdateItems].[Balance],");
            procedure.AppendLine("             [UpdateItems].[Price], [UpdateItems].[Currency], [UpdateItems].[Multiplicity],");
            procedure.AppendLine("             [UpdateItems].[HasPhotos], [UpdateItems].[DateOfCreation], [UpdateItems].[LastUpdated],");
            procedure.AppendLine("             [UpdateItems].[ForceUpdated], [UpdateItems].[Status], [UpdateItems].[LastUpdatedStatus],");
            procedure.AppendLine("             [Directories].[Id]");
            procedure.AppendLine("      FROM @catalogs AS [UpdateItems]");
            procedure.AppendLine("      LEFT JOIN [BrandItemEntities] AS [BrandItems] ON [UpdateItems].[Brand_Id] = [BrandItems].[Id]");
            procedure.AppendLine("      LEFT JOIN [DirectoryEntities] AS [Directories] ON [UpdateItems].[Directory_Id] = [Directories].[Id]");
            procedure.AppendLine("      WHERE [UpdateItems].[Id] NOT IN (SELECT [CatalogItems].[Id] FROM [CatalogItemEntities] AS [CatalogItems])");
            procedure.AppendLine(" ");
            procedure.AppendLine("      UPDATE [PhotoItems]");
            procedure.AppendLine("      SET [PhotoItems].[CatalogItem_Id] = [Link].[Catalog_Id]");
            procedure.AppendLine("      FROM [PhotoItemEntities] AS [PhotoItems]");
            procedure.AppendLine("      INNER JOIN @linkToPhotos AS [Link] ON [PhotoItems].[Id] = [Link].[Photo_Id]");
            procedure.AppendLine(" ");
            procedure.AppendLine("      SELECT [Id] FROM @catalogs;");
            procedure.AppendLine(" ");
            procedure.AppendLine("END");
            procedure.AppendLine("GO");
