            procedure.AppendLine("SET ANSI_NULLS ON");
            procedure.AppendLine("GO");
            procedure.AppendLine("SET QUOTED_IDENTIFIER ON");
            procedure.AppendLine("GO");
            procedure.AppendLine("CREATE PROCEDURE [dbo].[UpdateDirectories]");
            procedure.AppendLine("	@directories [dbo].[directoriesTable] READONLY");
            procedure.AppendLine("AS");
            procedure.AppendLine("BEGIN");
            procedure.AppendLine("--    +---------------------------------------------------+");
            procedure.AppendLine("--    | Author:       OLEXANDR LIKHOSHVA                  |");
            procedure.AppendLine("--    | Create date:  2018.02.25 01:15                    |");
            procedure.AppendLine("--    | Copyright:    © 2017-2018  ALL RIGHT RESERVED     |");
            procedure.AppendLine("--    | https://www.linkedin.com/in/olexandrlikhoshva/    |");
            procedure.AppendLine("--    |---------------------------------------------------|");
            procedure.AppendLine("--    | Description:  Procedure for insert or update      |");
            procedure.AppendLine("--    |               DirectoryEntities                   |");
            procedure.AppendLine("--    +---------------------------------------------------+");
            procedure.AppendLine("--    SET NOCOUNT ON added to prevent extra result sets from");
            procedure.AppendLine("--    interfering with SELECT statements.");
            procedure.AppendLine("--    SET NOCOUNT ON;");
            procedure.AppendLine(" ");
            procedure.AppendLine("      WITH [DirectoriesForUpdate] AS (SELECT * FROM [DirectoryEntities] AS [DirectoryItems]");
            procedure.AppendLine("                                  WHERE [DirectoryItems].[Id] IN (SELECT [Id] FROM @directories))");
            procedure.AppendLine("      UPDATE [ItemsForUpdate]");
            procedure.AppendLine("      SET [ItemsForUpdate].[Code] = [UpdateItems].[Code],");
            procedure.AppendLine("          [ItemsForUpdate].[Name] = [UpdateItems].[Name],");
            procedure.AppendLine("          [ItemsForUpdate].[Parent_Id] = [UpdateItems].[Parent_Id],");
            procedure.AppendLine("          [ItemsForUpdate].[DateOfCreation] = [UpdateItems].[DateOfCreation],");
            procedure.AppendLine("          [ItemsForUpdate].[LastUpdated] = [UpdateItems].[LastUpdated],");
            procedure.AppendLine("          [ItemsForUpdate].[ForceUpdated] = [UpdateItems].[ForceUpdated]");
            procedure.AppendLine("      FROM [DirectoriesForUpdate] AS [ItemsForUpdate]");
            procedure.AppendLine("      INNER JOIN @directories AS [UpdateItems] ON [ItemsForUpdate].[Id] = [UpdateItems].[Id]");
            procedure.AppendLine(" ");
            procedure.AppendLine("      INSERT INTO  [DirectoriesForUpdate]");
            procedure.AppendLine("      ([Id], [Code], [Name], [Parent_Id], [DateOfCreation], [LastUpdated], [ForceUpdated])");
            procedure.AppendLine("      SELECT [InsertItems].[Id], [InsertItems].[Code], [InsertItems].[Name], [InsertItems].[Parent_Id],");
            procedure.AppendLine("             [InsertItems].[DateOfCreation], [InsertItems].[LastUpdated], [InsertItems].[ForceUpdated]");
            procedure.AppendLine("      FROM @directories AS [InsertItems]");
            procedure.AppendLine("      WHERE [InsertItems].[Id] NOT IN (SELECT [DirectoryItems].[Id] FROM [DirectoryEntities] AS [DirectoryItems])");
            procedure.AppendLine(" ");
            procedure.AppendLine("      SELECT [Id] FROM @directories;");
            procedure.AppendLine(" ");
            procedure.AppendLine("END");
