            type.AppendLine("CREATE TYPE [dbo].[directoriesTable]  AS TABLE");
            type.AppendLine("( ");
            type.AppendLine("	[Id] [bigint] NOT NULL,");
            type.AppendLine("	[Code] [uniqueidentifier] NOT NULL,");
            type.AppendLine("	[Name] [nvarchar](255) NULL,");
            type.AppendLine("	[Parent_Id] [bigint] NULL,");
            type.AppendLine("	[DateOfCreation] [datetimeoffset](7) NOT NULL,");
            type.AppendLine("	[LastUpdated] [datetimeoffset](7) NOT NULL,");
            type.AppendLine("	[ForceUpdated] [datetimeoffset](7) NOT NULL,");
            type.AppendLine("    PRIMARY KEY ([Id])");
            type.AppendLine(")");
