//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatalogItemEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CatalogItemEntities()
        {
            this.PhotoItemEntities = new HashSet<PhotoItemEntities>();
            this.CommodityDirectionEntities = new HashSet<CommodityDirectionEntities>();
        }
    
        public long Id { get; set; }
        public System.Guid UID { get; set; }
        public string Code { get; set; }
        public string Article { get; set; }
        public string Name { get; set; }
        public string BrandName { get; set; }
        public string Unit { get; set; }
        public string EnterpriceNormPack { get; set; }
        public decimal BatchOfSales { get; set; }
        public string Balance { get; set; }
        public decimal Price { get; set; }
        public string Currency { get; set; }
        public decimal Multiplicity { get; set; }
        public bool HasPhotos { get; set; }
        public System.DateTimeOffset DateOfCreation { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
        public System.DateTimeOffset ForceUpdated { get; set; }
        public int Status { get; set; }
        public System.DateTimeOffset LastUpdatedStatus { get; set; }
        public Nullable<long> Brand_Id { get; set; }
        public Nullable<long> Directory_Id { get; set; }
        public Nullable<long> NomenclatureGroup_Id { get; set; }
    
        public virtual BrandItemEntities BrandItemEntities { get; set; }
        public virtual DirectoryEntities DirectoryEntities { get; set; }
        public virtual NomenclatureGroupEntities NomenclatureGroupEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PhotoItemEntities> PhotoItemEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CommodityDirectionEntities> CommodityDirectionEntities { get; set; }
    }
}
