//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class DirectoryEntities
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DirectoryEntities()
        {
            this.CatalogItemEntities = new HashSet<CatalogItemEntities>();
            this.DirectoryEntities1 = new HashSet<DirectoryEntities>();
            this.ProductDirectionEntities = new HashSet<ProductDirectionEntities>();
        }
    
        public long Id { get; set; }
        public System.Guid Code { get; set; }
        public string Name { get; set; }
        public System.DateTimeOffset DateOfCreation { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
        public System.DateTimeOffset ForceUpdated { get; set; }
        public Nullable<long> Parent_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CatalogItemEntities> CatalogItemEntities { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DirectoryEntities> DirectoryEntities1 { get; set; }
        public virtual DirectoryEntities DirectoryEntities2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDirectionEntities> ProductDirectionEntities { get; set; }
    }
}
