//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderEntities
    {
        public long Id { get; set; }
        public string OrderNumber { get; set; }
        public decimal Sum { get; set; }
        public int OrderStatus { get; set; }
        public string Comment { get; set; }
        public System.DateTimeOffset DateOfCreation { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
        public System.DateTimeOffset ForceUpdated { get; set; }
    }
}
