//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductDirectionEntities
    {
        public long Id { get; set; }
        public int Direction { get; set; }
        public System.DateTimeOffset DateOfCreation { get; set; }
        public System.DateTimeOffset LastUpdated { get; set; }
        public System.DateTimeOffset ForceUpdated { get; set; }
        public Nullable<long> Directory_Id { get; set; }
    
        public virtual DirectoryEntities DirectoryEntities { get; set; }
    }
}
