//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApplication4.DataService
{
    using System;
    using System.Collections.Generic;
    
    public partial class SendItemsEntities
    {
        public long Id { get; set; }
        public string Login { get; set; }
        public long EntityId { get; set; }
        public int EntityName { get; set; }
        public System.DateTimeOffset RequestDate { get; set; }
        public System.DateTimeOffset DateOfCreation { get; set; }
    }
}
